### ISSUE TITLE
Handling lines in pdfminer Plane may require modifications

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/pdftotree#10]
In #7, we significantly reduced the size of this repository by cutting `pdfminer` out of our repo and simply installing it as a dependency. Unfortunately, in the `extract_tables` utility, it appears that we needed modifications to the pdfminer library itself. Specifically, if we use `pdfminer.six` as is, we get this error:

```
[INFO] __main__ - Processing 1-s2.0-S003101829800159X-main.pdf (50 of 132)
ERROR:pdftotree.pdf.pdf_parsers:(184.194, 184.194, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/pdf/pdf_parsers.py", line 68, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv2/local/lib/python2.7/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv2/local/lib/python2.7/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv2/local/lib/python2.7/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv2/local/lib/python2.7/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (184.194, 184.194, 50)
```

when we try and extend the Plane with a box like 
```
<LTTextLineHorizontal 184.194,683.116,184.194,693.800 '(cid:211)\n'>]
```

This assertion is modified in the [original TreeStructure repo](https://github.com/HazyResearch/TreeStructure/blob/3bdd143358f3ec24d040c3aaa42fbbd2d10ab7aa/table-extraction/pdfminer/utils.py#L121-L125)

```py
def drange(v0, v1, d):
    """Returns a discrete range."""
    assert v0 <= v1
    return xrange(int(v0)//d, int(v1+d)//d)
```
to be `<=` rather than just `<`. There are likely other changes that were made to pdfminer itself in the TreeStructure repository. We should try and understand those changes, and see if it's possible to avoid them so that we don't have to have a duplicate of that library in our repo.

## Reproducing

On the `sen_ml` branch, you can run
```
extract_tables --train-pdf data/paleo/ml/train.pdf.list.paleo.not.scanned --gt-train data/paleo/ml/gt.train --test-pdf data/paleo/ml/test.pdf.list.paleo.not.scanned --gt-test data/paleo/ml/gt.test --datapath data/paleo/documents/ --model-path data/model.pkl -vv           
```

to see the error.

**Comment by lukehsiao** [comment]
Looks like Ines fixed this in TreeStructure: https://github.com/HazyResearch/TreeStructure/commit/27fc08cdd68b3aa8bd611cfa638a36ac1327166e

We'll need to do the same here.

**Comment by lukehsiao** [comment]
This is the next error Ines mentioned:

```
[INFO] __main__ - Processing 1107.full.pdf (95 of 132)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/.venv/bin/extract_tables", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lwhsiao/repos/pdftotree/bin/extract_tables", line 358, in <module>
    args.train_pdf, args.gt_train, args.datapath)
  File "/home/lwhsiao/repos/pdftotree/bin/extract_tables", line 92, in load_train_data
    X, y, tables = get_features_and_labels(pdf_list, gt_list, datapath)
  File "/home/lwhsiao/repos/pdftotree/bin/extract_tables", line 61, in get_features_and_labels
    bboxes, features, is_scanned = extractor.get_candidates_and_features()
  File "/home/lwhsiao/repos/pdftotree/pdftotree/ml/TableExtractML.py", line 132, in get_candidates_and_features
    page_num)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/ml/TableExtractML.py", line 152, in get_candidates_and_features_page_num
    font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/ml/features.py", line 124, in get_alignment_features
    boxes_figures, page_width, True)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (552.2, 552.2, 50)
```

**Comment by lukehsiao** [comment]
Second error fixed in https://github.com/HazyResearch/pdftotree/commit/a5c72edcdc3e2c4fa5fbb14a7fd39f40d6298b82
