### ISSUE TITLE
ModuleNotFoundError: No module named 'chardet'

### ISSUE THREAD

**Issue by santhosh0000000** [HazyResearch/pdftotree#118]
python3 paramspider.py --domain  
Traceback (most recent call last):
  File "/home/random/ParamSpider/paramspider.py", line 2, in <module>
    from core import requester
  File "/home/random/ParamSpider/core/requester.py", line 1, in <module>
    import requests
  File "/home/random/.local/lib/python3.9/site-packages/requests/__init__.py", line 44, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'

**Comment by santhosh0000000** [comment]
how can i fix it
