### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by chhenning** [HazyResearch/pdftotree#18]
Quick question. 
Does this project can be run on Windows? I have python 3.6.3. For now I'm only interested in the command line version. Do I still need python3-tk?

**Comment by lukehsiao** [comment]
Hi @chhenning, I suspect it can be, but I haven't tried. Feel feel to give it a go by installing it through pip. I'd be interested to hear if you run into any problems.

**Comment by chhenning** [comment]
Using python 2.7 I needed to install the following modules:
pdfminer
tabula-py
future
pandas
image
Wand
bs4
IPython

In addition Imagemagick needs to be installed. Here are the instructions:

http://docs.wand-py.org/en/0.4.3/guide/install.html#install-imagemagick-windows

So now when I run:
```
import pdftotree
pdftotree.parse("tests/input/paleo.pdf")
```

I get this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pdftotree\core.py", line 60, in parse
    pdf_html = extractor.get_html_tree()
  File "pdftotree\TreeExtract.py", line 212, in get_html_tree
    table_html = self.get_html_table(table, page_num)
  File "pdftotree\TreeExtract.py", line 308, in get_html_table
    area=table_str, output_format="json")
  File "C:\Python27\lib\site-packages\tabula\wrapper.py", line 92, in read_pdf
    return json.loads(output.decode(encoding))
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x96 in position 1597: invalid start byte
```

I have a feeling that this would work in python3. What is the preferred python env for you project?

**Comment by lukehsiao** [comment]
pdftotree is built for Python 3, yes.

**Comment by lukehsiao** [comment]
Hi @chhenning, 

On Ubuntu, that same command is not causing any issues. 
```
$ python
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdftotree
>>> result_html = pdftotree.parse("tests/input/paleo.pdf")
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C176 (2) in font CIPKGJ+AdvPSSym
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C211 (3) in font CIPKGJ+AdvPSSym
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C176 (2) in font CIPKGJ+AdvPSSym
Mar 10, 2018 8:27:22 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C211 (3) in font CIPKGJ+AdvPSSym
Mar 10, 2018 8:27:24 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C24 (3) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:24 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C24 (3) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:26 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:26 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:28 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:28 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C176 (2) in font CIPKGJ+AdvPSSym
Mar 10, 2018 8:27:28 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C0 (2) in font CIPKFI+AdvP4C4E74
Mar 10, 2018 8:27:28 PM org.apache.pdfbox.pdmodel.font.PDSimpleFont toUnicode
WARNING: No Unicode mapping for C176 (2) in font CIPKGJ+AdvPSSym
```

Unfortunately, I don't have any Windows machine to test that issue with at this time.

I noticed that your list of requirements is not the full list, though. How are you installing `pdftotree`?

**Comment by chhenning** [comment]
Yes my list is incomplete and only included modules which I haven't installed yet.

**Comment by chhenning** [comment]
For future references. A user needs to make sure that all packages mentioned in (requirements.txt)[https://github.com/HazyResearch/pdftotree/blob/master/requirements.txt] are installed.

**Comment by chhenning** [comment]
In any event, I switched to ubuntu to do some more testing.
