### ISSUE TITLE
AssertionError in pdfminer.six

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/pdftotree#19]
We have another AssertionError from pdfminer that we need to fix in `pdftotree`.
```
$ pdftotree -vv LITES00424-1.pdf 
[INFO] pdftotree.core - Digitized PDF detected, building tree structure...
INFO:pdftotree.core:Digitized PDF detected, building tree structure...
[ERROR] pdftotree.TreeExtract - (316.495, 316.495, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (316.495, 316.495, 50)
ERROR:pdftotree.TreeExtract:(316.495, 316.495, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (316.495, 316.495, 50)
```

**Comment by lukehsiao** [comment]
Another example output:

```
$ pdftotree -vv LITES00424-1.pdf 
[INFO] pdftotree.core - Digitized PDF detected, building tree structure...
INFO:pdftotree.core:Digitized PDF detected, building tree structure...
[ERROR] pdftotree.TreeExtract - (316.495, 316.495, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (316.495, 316.495, 50)
ERROR:pdftotree.TreeExtract:(316.495, 316.495, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (316.495, 316.495, 50)
```
