### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by chhenning** [HazyResearch/pdftotree#20]
The following simple test:
```
import os
import pdftotree

filename = '/home/chhenning/data/2N6N-0117.pdf'
htmlpath = '/home/chhenning/temp'

pdftotree.parse(filename, htmlpath, model_path=None, favor_figures=False, visualize=True)
```
creates the following output:

```
Digitized PDF detected, building tree structure
float division by zero
float division by zero
float division by zero
(89.33853599999992, 89.33853599999992, 50)
Traceback (most recent call last):
  File "chh_test.py", line 10, in <module>
    pdftotree.parse(filename, htmlpath, model_path=None, favor_figures=False, visualize=True)
  File "/home/chhenning/repos/pdftotree/pdftotree/core.py", line 57, in parse
    pdf_tree = extractor.get_tree_structure(model, favor_figures)
  File "/home/chhenning/repos/pdftotree/pdftotree/TreeExtract.py", line 195, in get_tree_structure
    favor_figures)
  File "/home/chhenning/repos/pdftotree/pdftotree/pdf/pdf_parsers.py", line 615, in parse_tree_structure
    figures_page = get_figures(mentions, elems.layout.bbox, page_num, boxes_figures, page_width, page_height)
  File "/home/chhenning/repos/pdftotree/pdftotree/pdf/pdf_parsers.py", line 945, in get_figures
    page_stat = Node(boxes)
  File "/home/chhenning/repos/pdftotree/pdftotree/pdf/node.py", line 44, in __init__
    self.set_bbox(bound_elems(elems))
  File "/home/chhenning/repos/pdftotree/pdftotree/pdf/vector_utils.py", line 101, in bound_elems
    group_x0 = min(map(lambda l:l.x0,elems))
ValueError: min() arg is an empty sequence
```

**Comment by lukehsiao** [comment]
Could you attach that file?

**Comment by chhenning** [comment]
Can I send it to you via email?

**Comment by lukehsiao** [comment]
Would prefer if you could attach to this issue to allow anyone to help debug.

**Comment by chhenning** [comment]
Yeah, sorry I cannot find it online and so I would rather not share it. Anyways, here is another one that throws errors.
[Summary of Benefits for BlueAdvantage HMO Plan on Pathway HMO Network.pdf](https://github.com/HazyResearch/pdftotree/files/1805084/Summary.of.Benefits.for.BlueAdvantage.HMO.Plan.on.Pathway.HMO.Network.pdf)

**Comment by chhenning** [comment]
btw, most of the files I try run into errors. Maybe it has something to do with the pdf generators my client is using?

**Comment by lukehsiao** [comment]
Great, thanks for that file. I'm seeing an IndexError there. As you can tell, `pdftotree` is still very much in development. We'll try to take a look at this soon.

**Comment by SenWu** [comment]
@chhenning Sure, we are very happy to debug with your data. You can send email to senwu@cs.stanford.edu

**Comment by lukehsiao** [comment]
Here is the more complete traceback:

```
$ pdftotree -vv 2N6N-0117.pdf 
[INFO] pdftotree.core - Digitized PDF detected, building tree structure...
[ERROR] pdftotree.TreeExtract - division by zero
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 39, in parse_layout
    char_width = get_char_width(boxes)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 1187, in get_char_width
    return box_len_sum / num_char_sum
ZeroDivisionError: division by zero
[ERROR] pdftotree.TreeExtract - division by zero
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 39, in parse_layout
    char_width = get_char_width(boxes)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 1187, in get_char_width
    return box_len_sum / num_char_sum
ZeroDivisionError: division by zero
[ERROR] pdftotree.TreeExtract - division by zero
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 39, in parse_layout
    char_width = get_char_width(boxes)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 1187, in get_char_width
    return box_len_sum / num_char_sum
ZeroDivisionError: division by zero
[ERROR] pdftotree.TreeExtract - (89.33853599999992, 89.33853599999992, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 148, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 67, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (89.33853599999992, 89.33853599999992, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/.venv/bin/pdftotree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lwhsiao/repos/pdftotree/bin/pdftotree", line 82, in <module>
    args.favor_figures, args.visualize)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/core.py", line 58, in parse
    pdf_tree = extractor.get_tree_structure(model, favor_figures)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 188, in get_tree_structure
    favor_figures)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 695, in parse_tree_structure
    boxes_figures, page_width, page_height)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 1108, in get_figures
    page_stat = Node(boxes)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/node.py", line 40, in __init__
    self.set_bbox(bound_elems(elems))
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/vector_utils.py", line 101, in bound_elems
    group_x0 = min(map(lambda l:l.x0,elems))
ValueError: min() arg is an empty sequence
```

**Comment by lukehsiao** [comment]
After the latest push on `bugfix`, we just have the assertion errors here.

```
$ pdftotree 2N6N-0117.pdf -vv
[INFO] pdftotree.core - Digitized PDF detected, building tree structure...
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 1.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes were found to cluster.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 2.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes were found to cluster.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 3.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes were found to cluster.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 4.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 5.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 6.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 13.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 14.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 15.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 17.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 18.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 19.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 20.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 21.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 22.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 23.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 24.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 25.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 26.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 27.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 28.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 29.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 30.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 31.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 32.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 33.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 34.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 35.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 36.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 38.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 40.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 41.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 42.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 43.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 44.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 46.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 47.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 49.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 50.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 52.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 53.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 54.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 55.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 58.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 59.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 60.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 61.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 62.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 63.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 65.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 66.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 67.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 68.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 69.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 70.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 71.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 72.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 73.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 74.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 76.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 78.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 80.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 81.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 82.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 83.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 84.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 85.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 86.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 87.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 88.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 89.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 90.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 91.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 93.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 94.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 95.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 96.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 98.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 99.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 100.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 101.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 102.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 103.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 104.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 105.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 106.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 107.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 108.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 109.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 110.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 111.
[ERROR] pdftotree.TreeExtract - (89.33853599999992, 89.33853599999992, 50)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 149, in get_candidates_alignments
    nodes, features = parse_layout(elems, font_stat)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 56, in parse_layout
    boxes_segments, boxes_curves, boxes_figures, page_width, combine)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 72, in cluster_vertically_aligned_boxes
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (89.33853599999992, 89.33853599999992, 50)
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 113.
[INFO] pdftotree.utils.pdf.layout_utils - No boxes were found on page 114.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes to get figures from on page 2.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes to get figures from on page 3.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No text found. Defaulting to char_width = 2.0.
[WARNING] pdftotree.utils.pdf.pdf_parsers - No boxes to get figures from on page 4.
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/.venv/bin/pdftotree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lwhsiao/repos/pdftotree/bin/pdftotree", line 82, in <module>
    args.favor_figures, args.visualize)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/core.py", line 58, in parse
    pdf_tree = extractor.get_tree_structure(model, favor_figures)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 189, in get_tree_structure
    favor_figures)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 697, in parse_tree_structure
    boxes_figures, page_width, page_height)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_parsers.py", line 1107, in get_figures
    plane.extend(boxes)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 341, in extend
    self.add(obj)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 346, in add
    for k in self._getrange((obj.x0, obj.y0, obj.x1, obj.y1)):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 334, in _getrange
    for x in drange(x0, x1, self.gridsize):
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/utils.py", line 171, in drange
    assert v0 < v1, str((v0, v1, d))
AssertionError: (89.33853599999992, 89.33853599999992, 50)
