### ISSUE TITLE
OverflowError: Python int too large to convert to C long in pdfminer.six

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/pdftotree#24]
```
$ pdftotree -vv MOTOS03160-1.pdf 
--- Logging error ---
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_utils.py", line 117, in analyze_pages
    interpreter.process_page(page)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 194, in get_font
    font = PDFType1Font(self, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 588, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 547, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 61, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 21, in name2unicode
    return six.unichr(int(m.group(0)))
OverflowError: Python int too large to convert to C long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 980, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 830, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 567, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 330, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/lwhsiao/repos/pdftotree/.venv/bin/pdftotree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lwhsiao/repos/pdftotree/bin/pdftotree", line 82, in <module>
    args.favor_figures, args.visualize)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/core.py", line 56, in parse
    if (not extractor.is_scanned()):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 104, in is_scanned
    self.parse()
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 79, in parse
    for page_num, layout in enumerate(analyze_pages(self.pdf_file)):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_utils.py", line 119, in analyze_pages
    log.exception(oe, ', skipping page', page_num, 'of', file_name)
Message: OverflowError('Python int too large to convert to C long',)
Arguments: (', skipping page', 0, 'of', 'MOTOS03160-1.pdf')

...
```

**Comment by lukehsiao** [comment]
```
pdftotree -vv MOTOS03160-1.pdf 
[ERROR] pdftotree.utils.pdf.pdf_utils - Python int too large to convert to C long, skipiping page 0 of MOTOS03160-1.pdf
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_utils.py", line 125, in analyze_pages
    interpreter.process_page(page)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 194, in get_font
    font = PDFType1Font(self, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 588, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 547, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 61, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 21, in name2unicode
    return six.unichr(int(m.group(0)))
OverflowError: Python int too large to convert to C long
[ERROR] pdftotree.utils.pdf.pdf_utils - Python int too large to convert to C long, skipiping page 1 of MOTOS03160-1.pdf
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/pdftotree/utils/pdf/pdf_utils.py", line 125, in analyze_pages
    interpreter.process_page(page)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 852, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 862, in render_contents
    self.init_resources(resources)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 362, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdfinterp.py", line 194, in get_font
    font = PDFType1Font(self, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 588, in __init__
    PDFSimpleFont.__init__(self, descriptor, widths, spec)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/pdffont.py", line 547, in __init__
    self.cid2unicode = EncodingDB.get_encoding(name, diff)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 61, in get_encoding
    cid2unicode[cid] = name2unicode(x.name)
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/pdfminer/encodingdb.py", line 21, in name2unicode
    return six.unichr(int(m.group(0)))
OverflowError: Python int too large to convert to C long
[ERROR] pdftotree.utils.pdf.pdf_utils - Python int too large to convert to C long, skipiping page 2 of MOTOS03160-1.pdf
```

**Comment by jtlz2** [comment]
Any update on this one? :\

**Comment by jtlz2** [comment]
What is causing it and is there a workaround?

**Comment by HiromuHota** [comment]
I tried to reproduce this but was successful...

macOS: 10.15.6
python: 3.7.3
pdfminer.six: 20200726
pdftotree: 0.4.0

I did a quick search and found this: https://github.com/pdfminer/pdfminer.six/issues/177
Seems like the issue was fixed by https://github.com/pdfminer/pdfminer.six/pull/263 at version 20191020 of pdfminer.six.

@lukehsiao if you can confirm it too, this issue can be closed.

**Comment by lukehsiao** [comment]
Confirming I don't see this issue anymore, even with this specific document. Closing the issue.
