### ISSUE TITLE
NullPointerException in Tabula

### ISSUE THREAD

**Issue by lukehsiao** [HazyResearch/pdftotree#26]
```
$ pdftotree -vv PNJIS01186-1.pdf 
[INFO] pdftotree.core - Digitized PDF detected, building tree structure...
[INFO] pdftotree.TreeExtract - No boxes were found on page 3.
[INFO] pdftotree.core - Tree structure built, creating html...
Exception in thread "main" java.lang.NullPointerException
        at technology.tabula.ObjectExtractorStreamEngine$PointComparator.compare(ObjectExtractorStreamEngine.java:258)
        at technology.tabula.ObjectExtractorStreamEngine.strokeOrFillPath(ObjectExtractorStreamEngine.java:219)
        at technology.tabula.ObjectExtractorStreamEngine.strokePath(ObjectExtractorStreamEngine.java:140)
        at org.apache.pdfbox.contentstream.operator.graphics.StrokePath.process(StrokePath.java:36)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:838)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:495)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
        at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150)
        at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:26)
        at technology.tabula.PageIterator.next(PageIterator.java:29)
        at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:157)
        at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:120)
        at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:101)
        at technology.tabula.CommandLineApp.main(CommandLineApp.java:71)
Traceback (most recent call last):
  File "/home/lwhsiao/repos/pdftotree/.venv/bin/pdftotree", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/lwhsiao/repos/pdftotree/bin/pdftotree", line 90, in <module>
    args.favor_figures, args.visualize)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/core.py", line 58, in parse
    pdf_html = extractor.get_html_tree()
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 209, in get_html_tree
    table_html = self.get_html_table(table, page_num)
  File "/home/lwhsiao/repos/pdftotree/pdftotree/TreeExtract.py", line 305, in get_html_table
    area=table_str, output_format="json")
  File "/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/tabula/wrapper.py", line 75, in read_pdf
    output = subprocess.check_output(args)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-jar', '/home/lwhsiao/repos/pdftotree/.venv/lib/python3.5/site-packages/tabula/tabula-1.0.1-jar-with-dependencies.jar', '--pages', '1', '--guess', '--area', '477.859678,59.62255426,749.8268984,524.8058348723742', '--format', 'JSON', 'PNJIS01186-1.pdf']' returned non-zero exit status 1

```

**Comment by HiromuHota** [comment]
I tried to reproduce this but was successful...

macOS: 10.15.6
python: 3.7.3
pdfminer.six: 20200726
pdftotree: 0.4.0
tabula-py: 2.2.0
Java: AdoptOpenJDK 1.8.0_242

The stacktrace reported here looks similar to the one reported here https://github.com/tabulapdf/tabula-java/issues/198.

@lukehsiao if you can confirm it too, this issue can be closed.

**Comment by lukehsiao** [comment]
Yes, I can confirm that I don't see the error any more. Closing the issue.
