### ISSUE TITLE
AttributeError: module 'pdftotree' has no attribute 'parse'

### ISSUE THREAD

**Issue by mekacharan** [HazyResearch/pdftotree#46]
I am trying to use the pdftotree in windows. I am getting the below error
AttributeError: module 'pdftotree' has no attribute 'parse'

**Comment by lukehsiao** [comment]
Please provide all the information necessary to reproduce this bug. We haven't tested pdftotree on Windows, and only directly test on OS X and Ubuntu. If you can include information on how you installed pdftotree, details about your environment, and the actual error log, someone may be able to help.

**Comment by EduardoNatale** [comment]
I got the same problem. I'm using Pop! os the same of Ubuntu. I've executed the command bellow
- sudo apt install python3-tk

After that I've executed the command bellow too
- pip install pdftotree

All this in a venv

```
import pdftotree
pdftotree.parse("blai.pdf", html_path=None, model_type=None, model_path=None, favor_figures=True, visualize=False)
```
This is how I got this error
AttributeError: module 'pdftotree' has no attribute 'parse'

So, now do you know how can I resolve this problem ?

**Comment by lukehsiao** [comment]
Can you attach `blai.pdf`?

**Comment by EduardoNatale** [comment]
Sure, no problem
[blai.pdf](https://github.com/HazyResearch/pdftotree/files/2915895/blai.pdf)

**Comment by lukehsiao** [comment]
Which version of `pdftotree` do you have? Unfortunately, I'm not able to reproduce this issue on my machine following your same steps (though I did notice that `chardet` needs to be added as a dependency to the pdftotree package).

**Comment by EduardoNatale** [comment]
I executed
- pip freeze or pip list (the same result)

`pdftotree==0.4.0`

**Comment by HiromuHota** [comment]
Closing for inactivity and irreproducibility.

**Comment by kcherneha** [comment]
@HiromuHota, @lukehsiao , hi! Have the same problem on pdftotree 0.4.1

**Comment by HiromuHota** [comment]
@kcherneha can you attach a PDF file that reproduces this issue?

**Comment by HiromuHota** [comment]
I tried to reproduce this issue on Windows 10 but couldn't.
- Install Python 3.8.6 (using Windows x86-64 executable installer)
- Install pdftotree (0.4.1) using pip
- Install ImageMagick (using ImageMagick-7.0.10-31-Q16-HDRI-x64-dll.exe)
- Open Python console from command-prompt:

```
D:\Users\hiromu\Downloads>python
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdftotree
>>> dir(pdftotree)
['TreeExtract', 'TreeVisualizer', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'core', 'logging', 'ml', 'parse', 'utils']
>>> pdftotree.parse()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: parse() missing 1 required positional argument: 'pdf_file'
```

I can see that `pdftotree` has `parse` method and looks functioning.

**Comment by kcherneha** [comment]
@HiromuHota, thanks for quick replying.
I use Ubuntu 18.04, python 3.6.9

Attached sample.pdf 
[sample.pdf](https://github.com/HazyResearch/pdftotree/files/5319730/sample.pdf)

**Comment by HiromuHota** [comment]
@kcherneha thanks for info.
So do you still have "pdftotree.py" in the current directory? If so, this makes that you have this issue.

To confirm, please execute `python -c "import pdftotree; print(pdftotree.__file__)"`. This command will tell which pdftotree module is in use.

**Comment by kcherneha** [comment]
@HiromuHota, /home/kyrylo/.local/lib/python3.6/site-packages/pdftotree/__init__.py
Seems like OK with pdftotree location, but still has empty output for sample.pdf file.

**Comment by HiromuHota** [comment]
@kcherneha 
I tested the sample.pdf that you attached and found that pdftotree (as of v0.4.1) recognized it as a scanned document.
This is why you got nothing.

```
$ python -c "import pdftotree; print(pdftotree.__version__)"
0.4.1
$ pdftotree ~/Downloads/sample.pdf 
[ERROR] pdftotree.core - Document is scanned, cannot build tree structure
HTML output to None
```

This issue has been fixed already #71 and will be available once v0.5.0 gets released.
You can also try it today by installing the pre-release version `pip install git+https://github.com/HazyResearch/pdftotree.git`.

**Comment by kcherneha** [comment]
@HiromuHota, thanks, it works for sample.pdf.
But, I have more complicated pdf, I can't send you them, cause they are under NDA, so, can tell, that they are scanned, too. And have some gray and colorful images with tables. Got such error:
`Traceback (most recent call last):
  File "test_pdftotree.py", line 3, in <module>
    pdftotree.parse('NDA
.pdf', "out-5.html", model_type=None, model_path=None, favor_figures=True, visualize=False)
  File "/home/kyrylo/.local/lib/python3.6/site-packages/pdftotree/core.py", line 69, in parse
    pdf_html = extractor.get_html_tree()
  File "/home/kyrylo/.local/lib/python3.6/site-packages/pdftotree/TreeExtract.py", line 277, in get_html_tree
    "title", f"bbox 0 0 {int(pwidth)} {int(pheight)}; ppageno {page_num-1}"
UnboundLocalError: local variable 'pwidth' referenced before assignment
`
Could you please tell, when it will be fixed and released?

**Comment by HiromuHota** [comment]
@kcherneha I reported this issue at #72 . Please keep an eye on it.
A scanned document has been out of scope of this project. It is on my radar but not in the immediate future.

**Comment by kcherneha** [comment]
@HiromuHota, ok, thanks for your answer.
