### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'PDFObjRef' and 'bytes'

### ISSUE THREAD

**Issue by adarsa** [HazyResearch/pdftotree#58]
When calling  pdftotree.parse(pdf_file), i get the following error:
>>> output = pdftotree.parse('403000541.pdf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdftotree/core.py", line 63, in parse
    if not extractor.is_scanned():
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdftotree/TreeExtract.py", line 121, in is_scanned
    self.parse()
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdftotree/TreeExtract.py", line 91, in parse
    for page_num, layout in enumerate(analyze_pages(self.pdf_file)):
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdftotree/utils/pdf/pdf_utils.py", line 136, in analyze_pages
    interpreter.process_page(page)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 841, in process_page
    self.render_contents(page.resources, page.contents, ctm=ctm)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 852, in render_contents
    self.init_resources(resources)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 356, in init_resources
    self.fontmap[fontid] = self.rsrcmgr.get_font(objid, spec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 204, in get_font
    font = self.get_font(None, subspec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdfinterp.py", line 195, in get_font
    font = PDFCIDFont(self, spec)
  File "/Users/adarsa/ilimi/pyenv36/lib/python3.6/site-packages/pdfminer/pdffont.py", line 641, in __init__
    self.cidcoding = (self.cidsysteminfo.get('Registry', 'unknown') + b'-' +
TypeError: unsupported operand type(s) for +: 'PDFObjRef' and 'bytes'

I installed by building the package in python 3.6.

**Comment by HiromuHota** [comment]
This issue looks no longer valid.
- This issue was reported at https://github.com/euske/pdfminer/issues/258 too, which was supposedly fixed by https://github.com/euske/pdfminer/commit/cc7d409d811d199bc510245ad0e01958161d06b4.
- This issue was reported when using pdfminer but the current pdftotree (v0.4.0) uses pdfminer.six.
