### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by AshutoshUpadhya** [HazyResearch/pdftotree#59]
**Describe the bug**
While running the extract_tables example,, I am getting the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/wand/cdefs/wandtypes.py", line 33, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
Exception ignored in: <bound method c_magick_char_p.__del__ of c_magick_char_p(13662016)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/wand/cdefs/wandtypes.py", line 33, in __del__
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable
```

I checked online but the solutions are not working here
Can someone pls suggest any solution. Thanks

**To Reproduce**
Execute following lines : 
```
 sudo extract_tables --train-pdf paleo/ml/train.pdf.list.paleo.not.scanned --gt-train paleo/ml/gt.train --test-pdf paleo/ml/test.pdf.list.paleo.not.scanned --gt-test paleo/ml/gt.test --datapath paleo/documents/ --model-path model.pkl
```
If necessary, attach example data which can be used to replicate the issue.

**Expected behavior**
The code should not fail.

**Error Logs/Screenshots**
If applicable, add error logs or screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS:   Ubuntu 16.04
 - `pdftotree` Version:  The latest master branch as of today(not sure of exact now)

**Comment by AshutoshUpadhya** [comment]
@lukehsiao : I tried all approaches I can search on stackoverflow, nbut its not working. Mostly they say abount python closing before environment close. I tried doing that but not successful. Can you pls see

**Comment by lukehsiao** [comment]
What python version are you using? Can you install pdftotree withing a virtual environment, rather than as sudo on your machine?

**Comment by HiromuHota** [comment]
From the original error messages and the report date, I can see:
1. Python 3.5
2. Wand 0.5.0 - 0.5.7 (`wand/cdefs/wandtypes.py` was added at 0.5.0 and 0.5.8 was released on December 5th, 2019).

Other than that, I cannot find anything else.
Closing for now but feel free to reopen when this issue still persists.
